Token Refresh
JoshuaMulliken/wyzeapy pull request #17
Opened 2021-08-25 01:46 UTC by yoinx

This change should prevent multiple threads from trying to refresh the token at the same time.

Additionally, there's no reason to refresh the token hourly when it's good for 60 hours, so we should be fine refreshing every 48 hours. I don't seem much reason to check that the refresh token is still valid since it is good for ~2 years. At that point... a user should really expect to have to re-login. 

These changes should make it a little easier to store the tokens externally and pass them back to the library so that a re-login is not required each time the library is re-initialized by an application. The token will just need to be passed back in during the create() call.

2021-08-25 03:09 UTC, JoshuaMulliken requested changes
Overall great change! Just need a couple fixes to make it work correctly.

2021-08-25 03:09 UTC, JoshuaMulliken commented on src/wyzeapy/wyze_auth_lib.py
> +    async def should_refresh(self) -> bool:
Since this is changing to be async it needs to be awaited.

2021-08-25 03:09 UTC, JoshuaMulliken commented on src/wyzeapy/wyze_auth_lib.py
> +                if self.should_refresh:
We need to await this here

2021-08-25 21:59 UTC, JoeSchubert commented on src/wyzeapy/wyze_auth_lib.py
> +    async def should_refresh(self) -> bool:
you're right, I messed that up somehow.

2021-08-25 21:59 UTC, JoeSchubert commented on src/wyzeapy/wyze_auth_lib.py
> +                if self.should_refresh:
It won't once I changed the previous comment back to not being async :s

2021-09-03 19:37 UTC, JoshuaMulliken approved these changes
Looks great! Thanks for the contribution!

2021-09-03 19:39 UTC, JoshuaMulliken requested changes
Hey @yoinx we get some merge conflicts can you take a look. I think it is because I merged the 2fa part and they both changed some of the same code

2021-09-03 20:41 UTC, yoinx commented
Things got messed up here...

2021-09-03 20:41 UTC, closed without merging